## Creating a numpy array

In [8]:
import numpy as np

#1D array
arr1 = np.array([1,2,3,4,5])
print("1D array: ")
print(arr1)

#2D array
arr2 = np.array([[1,2,3,4,5],
                [6,7,8,9,10]])
print("2D array: ")
print(arr2)

#3D array
arr3 = np.array([[[1,2,3,4,5],
                [6,7,8,9,10]],

                [[11,12,13,14,15],
                [16,17,18,19,20]],

                [[21,22,23,24,25],
                [26,27,28,29,30]]])
print("3D array: ")
print(arr3)

1D array: 
[1 2 3 4 5]
2D array: 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3D array: 
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]]


## Attributes

In [ ]:
# Dimention
print(f"Dimention of arr1 is: ", arr1.ndim)
print(f"Dimention of arr2 is: ", arr2.ndim)
print(f"Dimention of arr3 is: ", arr3.ndim)

DImention of arr1 is:  1
DImention of arr2 is:  2
DImention of arr3 is:  3


In [ ]:
# Shape
print(f"Shape of arr1 is: ", arr1.shape) #Column
print(f"Shape of arr2 is: ", arr2.shape) #Row, Column
print(f"Shape of arr3 is: ", arr3.shape) #Height, Row, Column

Shape of arr1 is:  (5,)
Shape of arr2 is:  (2, 5)
Shape of arr3 is:  (3, 2, 5)


In [ ]:
# Size (Total number of element)
print(f"Size of arr1 is: ", arr1.size)
print(f"Size of arr2 is: ", arr2.size)
print(f"Size of arr3 is: ", arr3.size)

Size of arr1 is:  5
Size of arr2 is:  10
Size of arr3 is:  30


In [14]:
# Data Type
demo = np.array([1,2.5,3,4])
demo1 = np.array([1, 4.7, "Hi", True])

print(f"Data type of arr1 is: ", arr1.dtype)
print(f"Data type of demo is: ", demo.dtype)
print(f"Data type of demo1 is: ", demo1.dtype)

Data type of arr1 is:  int64
Data type of demo is:  float64
Data type of demo1 is:  <U32


## Creating ndarray from existing data

In [22]:
# From list
lst = [1,2,3,4,5]
arr = np.array(lst, dtype=np.int64)
print(arr)
print(arr.dtype , "\n")

lst = [1,2,3.9,4,5]
arr = np.array(lst)
print(arr)
print(arr.dtype, "\n")

lst = [1,False,3.3,4,"Hii"]
arr = np.array(lst)
print(arr)
print(arr.dtype , "\n")

matrix = [[1,2,3],[4,5,6]]
mat = np.array(matrix)
print(mat)
print(mat.ndim, " , " ,mat.shape)

[1 2 3 4 5]
int64 

[1.  2.  3.9 4.  5. ]
float64 

['1' 'False' '3.3' '4' 'Hii']
<U32 

[[1 2 3]
 [4 5 6]]
2  ,  (2, 3)


In [25]:
# From Tuple
tpl = (10,20,30)
arr = np.array(tpl)
print(arr)
print(arr.dtype, "\n")

tpl = (10,20,30.55)
arr = np.array(tpl)
print(arr)
print(arr.dtype, "\n")

tpl = (10,20,30.55)
arr = np.asarray(tpl)
print(arr)
print(arr.dtype, "\n")

[10 20 30]
int64 

[10.   20.   30.55]
float64 

[10.   20.   30.55]
float64 



In [26]:
#From Set (must be converted to list)
st = {1,2,3}
arr = np.array(list(st))
print(st)
print(arr.shape)

{1, 2, 3}
(3,)


In [32]:
# From DIctionary
dc = {'a':10, 'b':20, 'c':30}
arr = np.array(dc.keys())
print(arr)
print(arr.dtype, "\n")

arr = np.array(dc.values())
print(arr)
print(arr.dtype, "\n")

arr = np.array(dc.items())
print(arr)
print(arr.dtype, "\n")

dict_keys(['a', 'b', 'c'])
object 

dict_values([10, 20, 30])
object 

dict_items([('a', 10), ('b', 20), ('c', 30)])
object 



## Random array creation with NumPy

In [ ]:
arr = np.random.rand(2,3)
print(arr)
# It will create a 2X3 matrix with random values form 0 -> 1 (float)

[[0.7981839  0.82976864 0.16585184]
 [0.25464844 0.43758385 0.36142627]]


In [ ]:
arr = np.random.randint(1,10,(2,3))
print(arr)
# It will create a 2X3 matrix with random values form 1 -> 9 (int)

[[3 2 8]
 [2 2 8]]


In [ ]:
arr = np.random.uniform(1,10,(2,3))
print(arr)
# It will create a 2X3 matrix with random values form 1 -> 9 (float)

[[5.13957153 4.57119685 4.5747506 ]
 [7.8835949  2.01273106 1.36549829]]


## Range Based array creation with NumPy

In [ ]:
arr = np.arange(1,10,3)
print(arr)
# np.arange(start, end, step)

[1 4 7]


In [ ]:
mat = np.array([1,2,3,4,5,6,7,8,9])
mat = mat.reshape(3,3)
print(mat)
# Total number of element must be same

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr = np.linspace(0,4,8)
print(arr)
# it wil create equally divided 8 numbers from 0 to 4

[0.         0.57142857 1.14285714 1.71428571 2.28571429 2.85714286
 3.42857143 4.        ]


In [ ]:
arr = np.logspace(0,4,6, base = 2)
print(arr)
# It will give logarithmically spread 6 values from 2^0 to 2^6

[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]


## Indexing and Slicing with NumPy

In [64]:
arr = np.array([1,2,3,4,5])
print(arr[4])

5


In [65]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr[0][2])

3


In [70]:
# Slicing
arr = np.array([1,2,3,4,5,6,7,8])
arr_mod = arr[1:4].copy() # arr[start:end:step]
#if donot use .copy() it will effect main array
print(arr_mod,"\n")

# arr[row_start:row_end:step , col_start:col_end:step]
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
row_0 = arr[0:1, ]
row_1 = arr[1:, ]
col_0 = arr[::,0:1]
col_1 = arr[::,1:2]

print(row_0 ,"\n", row_1, "\n\n", col_0, "\n\n", col_1)


[2 3 4] 

[[1 2 3 4 5]] 
 [[ 6  7  8  9 10]] 

 [[1]
 [6]] 

 [[2]
 [7]]


## Advance Indexing

In [71]:
lst = np.array([10, 20, 30, 40])
values = lst[[0, 3, 1]] #index
print(values)   

[10 40 20]


In [72]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[[0,1], [1,2]])
# - First list → row indices [0,1].
# - Second list → column indices [1,2].
# - Picks elements (0,1) and (1,2).

[2 8]


In [74]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[arr>3])
arr[arr == 4] = 0
print(arr)

[ 4  5  6  7  8  9 10]
[[ 1  2  3  0  5]
 [ 6  7  8  9 10]]


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for i in np.nditer(arr):
    print(i)

1  
2  
3  
4  
5  
6  
7  
8  
9  
10  
