Creating Tensor

In [5]:
import torch
print(torch.__version__)

2.14.0+cpu


In [6]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Device name {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not using")

GPU is not using


In [9]:
a = torch.empty(2, 3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
type(a)

torch.Tensor

In [11]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
torch.rand(2, 3)

tensor([[0.2614, 0.3542, 0.8273],
        [0.4184, 0.8523, 0.4295]])

In [16]:
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [18]:
torch.tensor( [[1,2,3], [4,5,6]] )

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [20]:
torch.arange(0,10, 2)

tensor([0, 2, 4, 6, 8])

In [22]:
torch.linspace(1, 10, 6)

tensor([ 1.0000,  2.8000,  4.6000,  6.4000,  8.2000, 10.0000])

In [23]:
x = torch.tensor( [ [1,2,3], [4,5,6] ] )
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [24]:
x.shape

torch.Size([2, 3])

In [33]:
torch.empty_like(x)

tensor([[4344896490928,             0,             0],
        [            0,             0,             0]])

In [34]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [35]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [40]:
torch.rand_like(x, dtype= torch.float32)

tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])

In [41]:
x.dtype

torch.int64

In [43]:
torch.tensor([1.0, 2.0, 3.0, 4.0], dtype=torch.int32)

tensor([1, 2, 3, 4], dtype=torch.int32)

In [44]:
x = x.to(torch.float32)
x.dtype

torch.float32

Mathmatical Operation

In [45]:
y = torch.tensor([[1,2,3], [4,5,6]])

In [46]:
y+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [47]:
y-2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [51]:
z = y*2
z

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [54]:
z/3

tensor([[0.6667, 1.3333, 2.0000],
        [2.6667, 3.3333, 4.0000]])

In [53]:
# floor
z // 3

tensor([[0, 1, 2],
        [2, 3, 4]])

In [55]:
# power
y**2

tensor([[ 1,  4,  9],
        [16, 25, 36]])

Element wise operation

In [56]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

In [57]:
a + b

tensor([[1.4812, 0.9536, 0.9538],
        [1.3137, 0.5332, 0.2568]])

In [58]:
a - b

tensor([[-0.4258, -0.4592,  0.6280],
        [-0.4667, -0.4994,  0.1850]])

In [59]:
a * b

tensor([[0.5032, 0.1746, 0.1288],
        [0.3770, 0.0087, 0.0079]])

In [60]:
a / b

tensor([[0.5534, 0.3499, 4.8557],
        [0.4757, 0.0327, 6.1557]])

In [61]:
a ** b

tensor([[0.5436, 0.3726, 0.9625],
        [0.4654, 0.1216, 0.9473]])

In [62]:
a % b

tensor([[0.5277, 0.2472, 0.1394],
        [0.4235, 0.0169, 0.0056]])

In [63]:
c = torch.tensor([1, -2, 3, -4])
torch.abs(c)

tensor([1, 2, 3, 4])

In [64]:
d = torch.tensor([1.4, 1.9, 2.1, 5.3, 6.7])
torch.round(d)

tensor([1., 2., 2., 5., 7.])

In [65]:
torch.ceil(d)

tensor([2., 2., 3., 6., 7.])

In [66]:
torch.floor(d)

tensor([1., 1., 2., 5., 6.])

In [67]:
torch.clamp(d, min= 0, max = 2)

tensor([1.4000, 1.9000, 2.0000, 2.0000, 2.0000])

Reduction Operation

In [71]:
e = torch.randint(size=(2, 3), low = 0, high=10, dtype= torch.float32)
e

tensor([[5., 9., 9.],
        [7., 5., 9.]])

In [73]:
torch.sum(e)

tensor(44.)

In [76]:
# column wise
torch.sum(e, dim=0)

tensor([12., 14., 18.])

In [77]:
# row wise
torch.sum(e, dim=1)

tensor([23., 21.])

In [74]:
torch.mean(e)

tensor(7.3333)

In [78]:
# row wise
torch.mean(e, dim = 0)

tensor([6., 7., 9.])

In [79]:
# column wise
torch.mean(e, dim = 1)

tensor([7.6667, 7.0000])

In [80]:
torch.median(e)

tensor(7.)

In [81]:
torch.max(e)

tensor(9.)

In [82]:
torch.min(e)

tensor(5.)

In [83]:
torch.prod(e)

tensor(127575.)

In [84]:
torch.std(e)

tensor(1.9664)

In [85]:
torch.var(e)

tensor(3.8667)

In [88]:
# Index of max number
torch.argmax(e)

tensor(1)

In [87]:
# Index of Min number
torch.argmin(e)

tensor(0)

Matrix Operation

In [ ]:
f = torch.randint(size=(2, 3), low = 0, high=10)
g = torch.randint(size=(2, 3), low = 0, high=10)

In [89]:
torch.matmul(f, g)

NameError: name 'f' is not defined

In [91]:
f = torch.randint(size=(2, 3), low = 0, high=10)
g = torch.randint(size=(3, 2), low = 0, high=10)

In [92]:
torch.matmul(f, g)

tensor([[170,  90],
        [115,  75]])

In [93]:
vector_1 = torch.tensor([1, 2])
vector_2 = torch.tensor([3, 4])

In [94]:
torch.dot(vector_1, vector_2)

tensor(11)

In [95]:
f.shape

torch.Size([2, 3])

In [97]:
f

tensor([[8, 9, 7],
        [9, 2, 6]])

In [96]:
torch.transpose(f, 0, 1)

tensor([[8, 9],
        [9, 2],
        [7, 6]])

In [108]:
h = torch.randint(size=(3, 3), low=0, high=10, dtype=torch.float32)
h

tensor([[6., 9., 2.],
        [3., 1., 0.],
        [2., 1., 2.]])

In [109]:
torch.det(h)

tensor(-40.)

In [110]:
torch.inverse(h)

tensor([[-0.0500,  0.4000,  0.0500],
        [ 0.1500, -0.2000, -0.1500],
        [-0.0250, -0.3000,  0.5250]])

Comparison Operation

In [114]:
i = torch.randint(size=(2, 3), low = 0, high=10)
j = torch.randint(size=(2, 3), low = 0, high=10)

In [115]:
i

tensor([[2, 7, 0],
        [2, 4, 4]])

In [116]:
j

tensor([[6, 2, 1],
        [0, 5, 1]])

In [117]:
i > j

tensor([[False,  True, False],
        [ True, False,  True]])

In [118]:
i < j

tensor([[ True, False,  True],
        [False,  True, False]])

In [119]:
i == j

tensor([[False, False, False],
        [False, False, False]])

In [120]:
i != j

tensor([[True, True, True],
        [True, True, True]])

Special Function

In [121]:
k = torch.tensor([10, 20, 30])
k

tensor([10, 20, 30])

In [122]:
torch.log(k)

tensor([2.3026, 2.9957, 3.4012])

In [123]:
torch.exp(k)

tensor([2.2026e+04, 4.8517e+08, 1.0686e+13])

In [124]:
torch.sqrt(k)

tensor([3.1623, 4.4721, 5.4772])

In [125]:
torch.sigmoid(k)

tensor([1.0000, 1.0000, 1.0000])

In [131]:
torch.softmax(k.float(), dim = 0)

tensor([2.0611e-09, 4.5398e-05, 9.9995e-01])

In [128]:
torch.relu(k)

tensor([10, 20, 30])

Inplace Operation

In [132]:
l = torch.rand(2,3)
m = torch.rand(2, 3)

In [133]:
l

tensor([[0.3124, 0.9431, 0.8519],
        [0.9815, 0.1132, 0.4783]])

In [134]:
m

tensor([[0.4436, 0.3847, 0.4521],
        [0.5569, 0.9952, 0.0015]])

In [135]:
l.add_(m)

tensor([[0.7560, 1.3279, 1.3039],
        [1.5384, 1.1084, 0.4798]])

In [136]:
l

tensor([[0.7560, 1.3279, 1.3039],
        [1.5384, 1.1084, 0.4798]])

In [137]:
torch.relu_(m)

tensor([[0.4436, 0.3847, 0.4521],
        [0.5569, 0.9952, 0.0015]])

In [138]:
m

tensor([[0.4436, 0.3847, 0.4521],
        [0.5569, 0.9952, 0.0015]])

Revise python's deep copy and shellow copy